/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignCampaignIdRulesRouteImport } from './routes/campaign.$campaignId.rules'
import { Route as CampaignCampaignIdPlayRouteImport } from './routes/campaign.$campaignId.play'
import { Route as CampaignCampaignIdLobbyRouteImport } from './routes/campaign.$campaignId.lobby'
import { Route as CampaignCampaignIdCharacterRouteImport } from './routes/campaign.$campaignId.character'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdRulesRoute = CampaignCampaignIdRulesRouteImport.update({
  id: '/campaign/$campaignId/rules',
  path: '/campaign/$campaignId/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdPlayRoute = CampaignCampaignIdPlayRouteImport.update({
  id: '/campaign/$campaignId/play',
  path: '/campaign/$campaignId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdLobbyRoute = CampaignCampaignIdLobbyRouteImport.update({
  id: '/campaign/$campaignId/lobby',
  path: '/campaign/$campaignId/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdCharacterRoute =
  CampaignCampaignIdCharacterRouteImport.update({
    id: '/campaign/$campaignId/character',
    path: '/campaign/$campaignId/character',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/campaign/$campaignId/character': typeof CampaignCampaignIdCharacterRoute
  '/campaign/$campaignId/lobby': typeof CampaignCampaignIdLobbyRoute
  '/campaign/$campaignId/play': typeof CampaignCampaignIdPlayRoute
  '/campaign/$campaignId/rules': typeof CampaignCampaignIdRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/campaign/$campaignId/character': typeof CampaignCampaignIdCharacterRoute
  '/campaign/$campaignId/lobby': typeof CampaignCampaignIdLobbyRoute
  '/campaign/$campaignId/play': typeof CampaignCampaignIdPlayRoute
  '/campaign/$campaignId/rules': typeof CampaignCampaignIdRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/create': typeof CreateRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/campaign/$campaignId/character': typeof CampaignCampaignIdCharacterRoute
  '/campaign/$campaignId/lobby': typeof CampaignCampaignIdLobbyRoute
  '/campaign/$campaignId/play': typeof CampaignCampaignIdPlayRoute
  '/campaign/$campaignId/rules': typeof CampaignCampaignIdRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character'
    | '/create'
    | '/lobby'
    | '/login'
    | '/play'
    | '/profile'
    | '/register'
    | '/rules'
    | '/campaign/$campaignId/character'
    | '/campaign/$campaignId/lobby'
    | '/campaign/$campaignId/play'
    | '/campaign/$campaignId/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character'
    | '/create'
    | '/lobby'
    | '/login'
    | '/play'
    | '/profile'
    | '/register'
    | '/rules'
    | '/campaign/$campaignId/character'
    | '/campaign/$campaignId/lobby'
    | '/campaign/$campaignId/play'
    | '/campaign/$campaignId/rules'
  id:
    | '__root__'
    | '/'
    | '/character'
    | '/create'
    | '/lobby'
    | '/login'
    | '/play'
    | '/profile'
    | '/register'
    | '/rules'
    | '/campaign/$campaignId/character'
    | '/campaign/$campaignId/lobby'
    | '/campaign/$campaignId/play'
    | '/campaign/$campaignId/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterRoute: typeof CharacterRoute
  CreateRoute: typeof CreateRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  CampaignCampaignIdCharacterRoute: typeof CampaignCampaignIdCharacterRoute
  CampaignCampaignIdLobbyRoute: typeof CampaignCampaignIdLobbyRoute
  CampaignCampaignIdPlayRoute: typeof CampaignCampaignIdPlayRoute
  CampaignCampaignIdRulesRoute: typeof CampaignCampaignIdRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/rules': {
      id: '/campaign/$campaignId/rules'
      path: '/campaign/$campaignId/rules'
      fullPath: '/campaign/$campaignId/rules'
      preLoaderRoute: typeof CampaignCampaignIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/play': {
      id: '/campaign/$campaignId/play'
      path: '/campaign/$campaignId/play'
      fullPath: '/campaign/$campaignId/play'
      preLoaderRoute: typeof CampaignCampaignIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/lobby': {
      id: '/campaign/$campaignId/lobby'
      path: '/campaign/$campaignId/lobby'
      fullPath: '/campaign/$campaignId/lobby'
      preLoaderRoute: typeof CampaignCampaignIdLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId/character': {
      id: '/campaign/$campaignId/character'
      path: '/campaign/$campaignId/character'
      fullPath: '/campaign/$campaignId/character'
      preLoaderRoute: typeof CampaignCampaignIdCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterRoute: CharacterRoute,
  CreateRoute: CreateRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  CampaignCampaignIdCharacterRoute: CampaignCampaignIdCharacterRoute,
  CampaignCampaignIdLobbyRoute: CampaignCampaignIdLobbyRoute,
  CampaignCampaignIdPlayRoute: CampaignCampaignIdPlayRoute,
  CampaignCampaignIdRulesRoute: CampaignCampaignIdRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
